# build.yml
on:  
  push:    
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - main          # triggers on pushes that contain changes in master       
  pull_request:
    branches-ignore: 
      - master
      - dev
      - develop
      - work
      - test

jobs:
  notify1:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Google Chat
        env:
          GOOGLE_CHAT_WEBHOOK: https://chat.googleapis.com/v1/spaces/AAAABZa6LiI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=aomqm1HUEYH1Ru00ixE8zWgLwcvMqFejM_FtxmzC6gc
        run: |
          EVENT_TYPE="${{ github.event_name }}"
          REPO="${{ github.repository }}"
          ACTOR="${{ github.actor }}"
          BRANCH="${GITHUB_REF##*/}"
          ACTION="${{ github.event.action }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
