# build.yml
on:  
  push:    
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
    - main          # triggers on pushes that contain changes in master       
  pull_request:
    branches-ignore: 
      - master
      - dev
      - develop
      - work
      - test

name: API Gateway Service Build and Push to ECR

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: shipeezi-gateway:${{ github.sha }}  
  APP_NAME: shipeezi-gateway-demo
  KUBE_NAMESPACE: Deployment
  KUBECTL_VERSION: "v1.23.6"
  IAM_VERSION: "0.5.5" 
